### ISSUE TITLE
Explorer crash

### ISSUE THREAD

**Issue by andreluizgit** [riverar/mach2#10]
Edited: Sorry... this bug was related with the 17661 OS build.

Explorer crash at every 2 minutes and it generate event 1000:

20h47
Nome do aplicativo com falha: explorer.exe, versão: 10.0.17661.1001, carimbo de data/hora: 0x00d09b84
Nome do módulo com falha: wevtapi.dll, versão: 10.0.17661.1001, carimbo de data/hora: 0xb1ae8222
Código de exceção: 0xc0000005
Deslocamento da falha: 0x0000000000013831
ID do processo com falha: 0xa5c
Hora de início do aplicativo com falha: 0x01d3e59451e97fbc
Caminho do aplicativo com falha: C:\WINDOWS\explorer.exe

20h45
Nome do aplicativo com falha: explorer.exe, versão: 10.0.17661.1001, carimbo de data/hora: 0x00d09b84
Nome do módulo com falha: wevtapi.dll, versão: 10.0.17661.1001, carimbo de data/hora: 0xb1ae8222
Código de exceção: 0xc0000005
Deslocamento da falha: 0x0000000000013831
ID do processo com falha: 0x2348
Hora de início do aplicativo com falha: 0x01d3e59406fadc15
Caminho do aplicativo com falha: C:\WINDOWS\explorer.exe

20h43
Nome do aplicativo com falha: explorer.exe, versão: 10.0.17661.1001, carimbo de data/hora: 0x00d09b84
Nome do módulo com falha: wevtapi.dll, versão: 10.0.17661.1001, carimbo de data/hora: 0xb1ae8222
Código de exceção: 0xc0000005
Deslocamento da falha: 0x0000000000013831
ID do processo com falha: 0x2760
Hora de início do aplicativo com falha: 0x01d3e593bbc9c258
Caminho do aplicativo com falha: C:\WINDOWS\explorer.exe

**Comment by riverar** [comment]
Known Windows issue; Upgrade to 17666+ https://blogs.windows.com/windowsexperience/2018/05/09/announcing-windows-10-insider-preview-build-17666/
