### ISSUE TITLE
What is the difference between?

### ISSUE THREAD

**Issue by awhorsky** [riverar/mach2#12]
What is the difference between always enabled and enabled by default, in the features texts? And which one do I enable for testing out features?

**Comment by riverar** [comment]
@awhorsky Sorry, just saw this. Always Enabled is always on, baked into the OS, cannot normally be turned off. Enabled By Default is a feature that is on/present but can be turned off (using `mach2 disable [id]`).

**Comment by awhorsky** [comment]
Which section do I use to enable new features to try out?

**Comment by riverar** [comment]
Always Enabled and Enabled by Default features are already enabled.
Disabled by Default features can be turned on
