### ISSUE TITLE
feature id for start menu pop up menu?....

### ISSUE THREAD

**Issue by stevencampoli** [riverar/mach2#14]
start menu hamburger pop up when mouse is hovering...what is the feature id for this...it disappeared this morning...

when you click start, hover mouse on left side a pop up menu comes out...

**Comment by WJXXBSH** [comment]
Try to enable 20455539 and revert 6395189?

**Comment by riverar** [comment]
Closing issue as it's old and isn't strictly related to mach2 tooling.
