### ISSUE TITLE
"unknown error" when trying to scan Windows Server 2019 symbols

### ISSUE THREAD

**Issue by johanbar** [riverar/mach2#17]
C:\Root\Mach2>mach2 scan c:\symbols -s -o features-found.txt
mach2 0.3 - Feature Control Multi-tool
Copyright (c) Rafael Rivera

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.

unknown error

It scans the symbols and fails ?

**Comment by riverar** [comment]
Seems related to #18, do you have msdia140.dll in the same folder? I haven't tried server symbols in a while, I'll check it out.

**Comment by johanbar** [comment]
Yes it's there, scans symbols and fails.

**Comment by riverar** [comment]
@johanbar What build of Windows Server 2019 are you working with? Will try this now.

**Comment by AnimMouse** [comment]
Run mach2 in administrator.

**Comment by riverar** [comment]
Closing stale issue; feel free to re-open if still a problem/needed.
