### ISSUE TITLE
"unknown error" when trying to enable/disable features

### ISSUE THREAD

**Issue by D3m3rion** [riverar/mach2#18]
Dumping the symbols worked great and the display command also does what it's supposed to be doing.
However, whenever I try to disable something, I'm getting the "unknown error" like on the screenshot.
I tried to find a solution through Google, but I was not able to find any reports of this.

I should add that I didn't compile the .exe myself but used one from the Internet. I tried to compile it, but I was getting a lot of errors on VS and eventually I gave up after a few hours.
That's probably the reason, but could you maybe confirm that? Is there a way to get a compiled .exe?

Any help would be appreciated!

![Untitled](https://user-images.githubusercontent.com/26471657/72707155-15fca700-3b60-11ea-8dea-dc0526a8e888.png)
Cheers!

**Comment by riverar** [comment]
Hey @D3m3rion pre-compiled binaries can be found on the Releases tab https://github.com/riverar/mach2/releases I suspect you're missing msdia140.dll?

**Comment by D3m3rion** [comment]
Thank you for your response!

This might be the case, where exactly does it need to be? It's present in the mach2 folder (where the .exe is) and in multiple Microsoft SDKs in thew x86 program files and Visual Studios folders.

**Comment by riverar** [comment]
@D3m3rion It just needs to be alongside the executable. If it's needed, it'll be loaded from there. (It's in the release zip linked to earlier.) That said, it's only needed when scanning so if scanning works, this won't be the culprit.

Can you paste the compilation errors? Should compile cleanly.

**Comment by AnimMouse** [comment]
Run it in administrator.

**Comment by riverar** [comment]
Closing stale issue; mach2 is deprecated and users on newer builds of Windows should use [vivetool](https://github.com/thebookisclosed/ViVe).
