### ISSUE TITLE
software mach2 doesnt work Windows 10 2004 solution needet

### ISSUE THREAD

**Issue by marko090591** [riverar/mach2#19]
mach2 had make it easier to find files in Windows 10, but that functionalty doesn't work in Windows 10 2004 as it worked in Windows 10 1909 (https://winaero.com/blog/restore-classic-search-in-file-explorer-in-windows-10-version-1909/). 
Windows New search is time-consuming (clicking enter every time when search is performed and search field in file explorer is lagy) .

**Comment by riverar** [comment]
This isn't a mach2 issue. Also, Microsoft has forced that feature on -- it can no longer be enabled.

**Comment by RedaBousserhane** [comment]
no work, windows 10 2004 :(

**Comment by riverar** [comment]
@RedaBousserhane Check out https://github.com/thebookisclosed/ViVe for Windows 10 2004.

**Comment by RedaBousserhane** [comment]
thank you

**Comment by marko090591** [comment]
Hellow 

What's the command line for input to CMD. its like below?


ViVeTool.exe addconfig 18755234 1

**Comment by parhamsan** [comment]
Hello marko090591,

Did you ever tested or figured it out if the command line works with ViVeTool.exe to bring back the old windows search on windows 2004 version.
I would appreciate if you can help.

Thanks.

**Comment by RedaBousserhane** [comment]
not working in Windows 10 (2004)

**Comment by riverar** [comment]
@RedaBousserhane As mentioned earlier, use https://github.com/thebookisclosed/ViVe for Windows 10 2004 and above.
