### ISSUE TITLE
Piping and/or Redirecting the output does not work

### ISSUE THREAD

**Issue by AnimMouse** [riverar/mach2#20]
When redirecting the output
`mach2 display > output.txt`
It shows:
```
mach2 0.3 - Feature Control Multi-tool
Copyright (c) Rafael Rivera

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.

Failed to ENABLE_VIRTUAL_TERMINAL_PROCESSING: The handle is invalid.
```
Failed to ENABLE_VIRTUAL_TERMINAL_PROCESSING: The handle is invalid.
I'm trying to make an automated feature 18755234 disabler that detects if that feature is enabled, but mach2 does not work on pipes.

**Comment by riverar** [comment]
@AnimMouse Thanks, will get this fixed tomorrow. Good catch.

**Comment by AnimMouse** [comment]
Thanks, the batch file that I made is now working.
