### ISSUE TITLE
Doesn't work on version 2004

### ISSUE THREAD

**Issue by commander443** [riverar/mach2#21]
I did all the steps and did a restart but the banner doesn't show up?

**Comment by renpag** [comment]
I've the same problem

**Comment by ChethiyaKMax** [comment]
Same here

**Comment by DarthJahus** [comment]
Yes. Mach2 isn't working. You might want to try [Vive](https://github.com/thebookisclosed/ViVe/releases).

**Comment by renpag** [comment]
I said that badly
match2 works, is the command "mach2 disable 18755234" that no longer works and does not restore the original version of the windows search....
what is the command to do it with Vive?

**Comment by DarthJahus** [comment]
I believe it's `delconfig`, @renpag

**Comment by riverar** [comment]
@renpag Because you want `revert`, see the documentation/help provided by the tool.

Feature Control has changed in Windows, see https://github.com/thebookisclosed/ViVe for more information.
