### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by matze19999** [riverar/mach2#22]
Can we get arm64 support, so we can use this on the surface pro x?

**Comment by riverar** [comment]
@matze19999 The x86 version should work fine but sure. I'll freshen up the project and CI/CD pipeline and provide arm64 builds.

**Comment by matze19999** [comment]
> @matze19999 The x86 version should work fine but sure. I'll freshen up the project and CI/CD pipeline and provide arm64 builds.

Thank you!
