### ISSUE TITLE
no effect on settings app ui on surface pro 7

### ISSUE THREAD

**Issue by nitishksh** [riverar/mach2#27]
this has no effect on settings app ui banner on surface pro 7. tried this through both cmd (administrator) and power shell (administrator).

**Comment by WhitieStuff** [comment]
No effect on 'disable 18715789'
Windows 10 Pro 2004 (19041.329)

**Comment by riverar** [comment]
See also https://github.com/riverar/mach2/issues/21#issuecomment-659973821
