### ISSUE TITLE
The operation completed successfully., system:0

### ISSUE THREAD

**Issue by MrDodojo** [riverar/mach2#29]
The integration of Capstone, vcpkg support or something in commit ce0080c inhibits me from getting an output from mach2 scans. When starting a scan `mach2 scan c:\symbols -s -o featuresfound.txt` it doesn't give an error, it just doesn't scan and doesn't create a featuresfound.txt. With as output: `The operation completed successfully., system:0 `
![image](https://user-images.githubusercontent.com/47711280/104089144-4dc69800-5264-11eb-84ce-49982fbf4074.png)

Building Mach2 pre this commit doesn't result in this issue, building from this commit and onwards does.

This could also be me doing something wrong(sorry already), does anyone here know why this occurs? Thanks

**Comment by riverar** [comment]
The included DIA requires the Visual C++ 2015 runtimes https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by MrDodojo** [comment]
I've actually download and installed that, didn't change a thing

**Comment by riverar** [comment]
That exact version linked above?

**Comment by MrDodojo** [comment]
The exact version above.

**Comment by riverar** [comment]
Strange. Sorry for the headaches.

Some questions:
* What OS build are you on?
* What does `regsvr32 msdia140.dll` show? (Just a quick "load the library and resolve dependencies" diagnostic hack in this case.)

In the meantime, I'll fire up a clean VM and re-test + work on documenting/eliminating the missing dependency.

**Comment by MrDodojo** [comment]
My current OS build is 21292.1010, 
Running `regsvr32 msdia140.dll` in the directory mach2.exe and msdia140.dll are located brings up a pop-up error `The module "msdia140.dll" failed to load. Make sure the binary is stored at the specific path or debug it to check for problems with the binary or dependent .DLL files. The specified module could not be found`

**Comment by riverar** [comment]
Does `MSVCP140.dll` exist on your box? (That's part of the Visual C++ 2015 runtimes.) Are you trying to use the x86 or x64 version of mach2? (You'll need to install the corresponding bitness runtime, i.e. x86 runtimes for mach2-x86.zip, x64 runtimes for mach2-x64.zip.)

**Comment by Imp0815** [comment]
I have the exact same problem. The Visual C++ 2015 runtime is installed and i get the same error when trying to run regsvr32 msdia140.dll.
Where should the MSVCP140.dll be?

I'm running Win10 Education x64 1909 Build 18363.1316

I'm trying to use mach2 x64.

**Comment by riverar** [comment]
Closing stale issue; doubt this is relevant anymore. Feel free to reopen/file a new bug if needed. (I plan on revamping this area so the problem will likely go away, if it still exists.)
