### ISSUE TITLE
Disable/Enable via registry

### ISSUE THREAD

**Issue by 7wgs0gr04v** [riverar/mach2#30]
How to disable/enable features via registry? There is this registry key which supposedly controls the features.

```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\0\2093230218]
"EnabledState"=dword:00000002
"EnabledStateOptions"=dword:00000000
```

**Comment by riverar** [comment]
Haven't looked into the newer overrides, try asking @thebookisclosed over at https://github.com/thebookisclosed/ViVe
