### ISSUE TITLE
capstone

### ISSUE THREAD

**Issue by knowhatamine** [riverar/mach2#33]
Very eager to check this one out after reading those testimonies 👍 

Alas, the entire capstone folder seems to be missing. (Cannot open include file: 'capstone/capstone.h': No such file or directory)

**Comment by riverar** [comment]
Closing stale issue; sounds like `vcpkg` wasn't run perhaps? Let me know if you continue to have issues!

**Comment by wisemoth** [comment]
This is a problem for me too:
```
> git rev-parse head
802f51d7cb3731826f508cd644c7ddac3cefc410
```
re-running `vcpkg` to confirm required packages installed for this comment (ran before successfully):
```
> ..\vcpkg\vcpkg.exe --feature-flags=manifests install
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
All requested packages are currently installed.
Restored 0 packages from C:\Users\XXXXXX\AppData\Local\vcpkg\archives in 236.2 us. Use --debug to see more details.

Total elapsed time: 13.43 s

The package capstone provides CMake targets:

    find_package(capstone CONFIG REQUIRED)
    target_link_libraries(main PRIVATE capstone::capstone)

The package cli11 provides CMake targets:

    find_package(CLI11 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CLI11::CLI11)
```
open solution in VS 2019, select any of x64/x86/Release/Debug; get build errors:
1) `Cannot open include file: 'capstone/capstone.h': No such file or directory`
2) `Cannot open include file: 'CLI/CLI.hpp': No such file or directory`
