### ISSUE TITLE
What are interesting hidden features we can modify with Mach2 ?

### ISSUE THREAD

**Issue by Kiraxelle** [riverar/mach2#39]
I know that we can disable the header banner in options thanks to : 
18299130

I know that we can stop auto expand of the start menu of Windows 10 thanks to : 
18715789

I know we can return to the previous appareance of the start menu thanks to : 
25478404

Except these three, do you have a list of all interesting hidden features to enable/disable ?

Or maybe just the most interesting ?

Thanks in advance.

**Comment by Kiraxelle** [comment]
No one knows ?

**Comment by nicolai1905** [comment]
Olso. Insider win11.  Can be interesting

**Comment by Shaughn-david** [comment]
What is the syntax for making the start menu return to the old design? I can't figure it out.

**Comment by riverar** [comment]
A list of features can be found at https://github.com/riverar/mach2/tree/master/features
