### ISSUE TITLE
Which Windows versions have those hidden features?

### ISSUE THREAD

**Issue by Biswa96** [riverar/mach2#4]
I've tried your current release in my PC with Windows build 17627. It doesn't show any feature with `display` option. I also tried it with a fresh Windows VM but it doesn't show any features. Which Windows builds have those hidden features?

**Comment by riverar** [comment]
`display` is used to show *configured* features; you likely won't have any on a fresh box. You can try turning on Sets, for example, via `mach2 enable 13849566 -v 1` and `mach2 enable 10727725 -v 1` (most features don't need variants, sets is an outlier in this case)

**Comment by Biswa96** [comment]
Where did you find those numbers? Can I remove the dependency of that msdia140.dll? I tried with multi threaded in Visual Studio but the dependency remains.

**Comment by riverar** [comment]
Check out https://github.com/riverar/mach2/tree/master/features. `msdia140.dll` cannot be removed at this time.

**Comment by Biswa96** [comment]
I saw that. But HOW did you find those numbers?

**Comment by riverar** [comment]
I just wrote a quick wiki article on downloading symbols (https://github.com/riverar/mach2/wiki/Download-Symbols). You can then use the `mach2 scan` subcommand to scan those symbol files. Be sure to look at `mach2 scan --help`.

**Comment by Biswa96** [comment]
Can understand the first step.

**Comment by Biswa96** [comment]
Can't understand the first step.  Also the symchk.exe doesn't present in normal Visual Studio installation. I've to download Windows SDK seperately to get that symchk.exe.

**Comment by riverar** [comment]
Download a Windows ISO and extract \sources\install.wim\... to a folder on disk. There are tutorials out there for this.

**Comment by Biswa96** [comment]
Another fact I saw in the source code. Enabling and disabling the feature doesn't need that msdia140.dll, it just need for .PDB files. Am I right?

**Comment by riverar** [comment]
Correct, it's used for scanning only, at this time.

**Comment by Biswa96** [comment]
There are too many .PDB files....
 BTW, did you check this repostiory https://github.com/microsoft/microsoft-pdb/. I use cvdump.exe from that repository and it shows same result as your (with using find command). 
But you didn't mention how did you get these undocumented Windows APIs? How did you get all those enums ad structs? Did you revese any system dll or exe (at night)?

**Comment by riverar** [comment]
cvdump does not produce the same results. I'm closing this issue. If you have an **issues** with the tool, feel free to report them. Thanks!

**Comment by Biswa96** [comment]
How do I know which feature ID enables corresponding features?

**Comment by riverar** [comment]
By reading the list mentioned earlier.

**Comment by Biswa96** [comment]
Not that relation. For example, you've told that using these feature ID 13849566 and 10727725 will enable sets. But the ID in features.txt says:
TabShellVisibility: 13849566
TabShell: 10727725 
So, how can I understand that TabShell is related to sets feature?

**Comment by Biswa96** [comment]
And what is the variants (-v option)? Should I add that in every enable or disable options?

**Comment by riverar** [comment]
I don't have any docs on this yet, but Features can be configured with extra variant-typed metadata that can be used for a multitude of things. For example, a Feature may use it in an A/B test situation to select which test to execute. If I remember correctly, Sets just uses it as an additional enabled/disabled layer at this time. This warrants more investigation on my part.

**Comment by Biswa96** [comment]
I can't redirect the output of `mach2 scan` to a file so that I can save the list in a text file.

**Comment by Biswa96** [comment]
I can't redirect the output of `mach2 scan` to a file so that I can save the list in a text file.  It shows handle error.  
There are many features with feature ID zero. Do they all enable if I use 0 as a feature ID in mach2?

**Comment by Biswa96** [comment]
@riverar I've a project which may speed up the PDB download. Link: https://github.com/Biswa96/PDBDownloader

**Comment by Biswa96** [comment]
I've a project which may speed up the PDB download procedure. May you check it?

**Comment by riverar** [comment]
@Biswa96 Will check it out tomorrow; what's the speed improvement? Multi-threaded or something?

**Comment by Biswa96** [comment]
No it just download the file faster than symchk. But I've tried it with so many file.

**Comment by riverar** [comment]
Do you have a link? I can't find it.

**Comment by Biswa96** [comment]
my profile......

**Comment by riverar** [comment]
Ah ok. I looked at https://github.com/Biswa96/PDBDownloader and it doesn't do anything different than Microsoft's symchk. Unless you have benchmark data that shows it's substantially faster, I can't spend time on this. Thanks!

**Comment by Biswa96** [comment]
OK, I'll inform if it is faster or not.
