### ISSUE TITLE
ID for 22509 Start Customization

### ISSUE THREAD

**Issue by 06Sonic** [riverar/mach2#41]
What is the ID for the new Start menu customization announced in 22509? Was trying to find it, but it isn't there.
![image](https://user-images.githubusercontent.com/95177021/144712096-cbc7a3a1-db29-4d20-b3ac-bc6611157009.png)

**Comment by Biswa96** [comment]
This article may help https://winaero.com/how-to-show-more-pins-or-recommendations-in-windows-11-start-menu/amp/

**Comment by riverar** [comment]
Closing as this isn't a mach2 issue but rather a usage question.
