### ISSUE TITLE
NavigationPaneExpandOnHover 18715789 disable is temporary

### ISSUE THREAD

**Issue by Zulkifilyusuf750** [riverar/mach2#42]
I notice that the change goes back to default after a system restart. Please can I know which file the change is made to, so I can set a custom security rule to prevent the system from modifying the configuration registry/file?
I really hate the feature. Thank you.

**Comment by riverar** [comment]
Hi @Zulkifilyusuf750, please refer to https://github.com/thebookisclosed/ViVe/issues/6
