### ISSUE TITLE
A Question about mach2 Scanning

### ISSUE THREAD

**Issue by PeterStrick** [riverar/mach2#43]
Hi there @riverar, I have a simple question about scanning .pdb Files using mach2.

Currently, I download the PDB Files using the following commands:

`C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symchk.exe /r "C:\Windows" /oc "C:\New Folder" /cn`
`C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symchk.exe /r "C:\Program Files" /oc "C:\New Folder" /cn`
`C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symchk.exe /r "C:\Program Files (x86)" /oc "C:\New Folder" /cn`

This results in the `C:\New Folder` Folder being populated with .pdb Files that amount to 24.4 GB in total

After that, mach2 is called using `Path/to/mach2.exe scan "C:\New Folder" -i "C:\New Folder" -o "C:\Users\Peter\Desktop\25136_scanned.txt" -u -s`

Although the resulted .txt File is different from the File in your Features directory, especially in the Unknown section.

Every ID in the Unknown Section of my own scanned file is 0, which I don´t understand why.

The IDs for the Always Enabled, Enabled By Default, Disabled By Default and Always Disabled are the same between them.

Do you have an idea of why the IDs in the Unknown section are all 0s?

mach2 Version is 0.7
Windows SDK used is 10.0.22000.194
Windows Build is 25136.1000

Files:
[25136_mach2repo.txt](https://github.com/riverar/mach2/files/8901419/25136_mach2repo.txt)
[25136_scanned.txt](https://github.com/riverar/mach2/files/8901422/25136_scanned.txt)
[difference between them.zip](https://github.com/riverar/mach2/files/8901434/difference.between.them.zip) - created with WinDiff

**Comment by riverar** [comment]
What I typically do is crack open a Windows ISO, and extract install.wim to a `Build` folder and provide that as input to Mach2.

**Comment by Biswa96** [comment]
Is it required to extract WIM file? I generally mount it with dism but I do not scan the entire WIM file, just some few files.

**Comment by riverar** [comment]
That works too. I find WIM I/O to be slow.

**Comment by PeterStrick** [comment]
> Hey @PeterStrick! `-i, --image-path` needs a folder of exes/dlls, not symbols. It will then disassemble each file, matched with its symbols, and look for these IDs.

Does the `-i` command work recursively?

**Comment by riverar** [comment]
Not a dumb question; yep it works recursively.

**Comment by PeterStrick** [comment]
> Not a dumb question; yep it works recursively.

Great! Maybe adding a hint that `-i` needs exe/dlls and not symbols in either the wiki or mach2 itself would be helpful, as I have mainly used these to craft the mach2 command syntax
