### ISSUE TITLE
I do not find and use id to enable feature in window 11 build 25201

### ISSUE THREAD

**Issue by kid1485** [riverar/mach2#46]
I do not find and use id  34300186 named WidgetsExpandedView to enable expanded view widget in window 11 Build 25201 Insider Preview Build for the Dev Channel, i hope you add these id to feature or find a way to add it

**Comment by WaterMelon4938** [comment]
Mach2 doesn’t work on Windows 11. Instead use https://github.com/thebookisclosed/ViVe/
