### ISSUE TITLE
Scan suddenly stops after scanning certain files. 

### ISSUE THREAD

**Issue by XenoPanther** [riverar/mach2#49]
I was attempting to scan build 25309's ARM64 build and when it reached the following files, the scan would stop:

1. System32\IME\IMJPPRED.DLL
2. System32\IME\IMJPTIP.DLL
3. System32\sndvolSSO.dll
4. System32\SettingsHandlers_nt.dll

I scanned the amd64 versions of these files without any issues

**Comment by riverar** [comment]
@XenoPanther Can you re-test with latest code in main? Not seeing that here.

**Comment by XenoPanther** [comment]
Will do that tomorrow for you

**Comment by XenoPanther** [comment]
Retried with 25314 using the current release as a control and the issue has resolved itself
