### ISSUE TITLE
Unable to grab IDs for 25915's setup

### ISSUE THREAD

**Issue by XenoPanther** [riverar/mach2#52]
This is the command I am running `mach2 scan "D:\Symbols\Setups\25915" -i "C:\Users\Xeno\Desktop\25915" -u` and it spits out feature names with IDs of 0
I tested this with 25905 using the same folder structures and I successfully get IDs

**Comment by riverar** [comment]
25915 IDs are in so going to close this for now. Happy to continue debugging with you in chat if needed. (Architecture difference? Typo somewhere?)
