### ISSUE TITLE
Readme is missing information about the tool compatible Windows Versions

### ISSUE THREAD

**Issue by gus33000** [riverar/mach2#54]
mach2 doesn't work with modern Windows OS builds, yet the readme doesn't acknowledge its compatibility list in regards to feature management/control. Scanning is not affected by any OS requirement and should also be mentioned

**Comment by riverar** [comment]
Yeah I need to just nuke all that functionality and point them to vivetool.

**Comment by gus33000** [comment]
So was there a change of mind? I don't see any commit doing what you said you would do and you just closed this as unplanned 🤔
