### ISSUE TITLE
Subcommands (e.g. enable, disable, revert) should accept multiple feature IDs

### ISSUE THREAD

**Issue by Kapranov98** [riverar/mach2#8]
I would like to see an option that disables all activated functions. Manually this is not very convenient

**Comment by Biswa96** [comment]
What about the value of feature id 0 (zero)?

**Comment by AnimMouse** [comment]
Solved this by making a batch file, and running mach2 several times in the batch file.

**Comment by riverar** [comment]
Closing stale enhancement; no longer needed. Users wishing to enable/disable features on newer builds of Windows should use [vivetool](https://github.com/thebookisclosed/ViVe).
