### ISSUE TITLE
Automatic generation of full and short log

### ISSUE THREAD

**Issue by Kapranov98** [riverar/mach2#9]
I suggest adding a parameter to automatically create a full log with PDB information in which a function is found, and a short log with information about the functions and their IDs.

**Comment by riverar** [comment]
Agree, I currently just call it twice which is pretty lame.

**Comment by Kapranov98** [comment]
Hmm, I create a full log and then delete the regular expression using Notepad ++.

**Comment by riverar** [comment]
After 4 years, I'm probably not going to get around to this. (That said, I do plan on rewriting this tool in Rust soon so will make sure this gets added then.)
